### ISSUE TITLE
Link to documentation in Description does not work

### ISSUE THREAD

**Issue by DanielOberlechner** [XmlmXmlmX/InkyTagHelpers#3]
Hi,
There is a link which sends you to the documentation which does not work...
Is maybe this link here the new one?
https://get.foundation/emails/docs/

This one does not work:
https://foundation.zurb.com/emails/docs/

It shows a error from Cloudfare: 522 server errror.

Do I've found the new correct link?

Kind regards,
Daniel :)

**Comment by XmlmXmlmX** [comment]
Hi @DanielOberlechner 
thanks for writing. Yes indeed, you've found the new link.
